#!/bin/bash
# List of environment variables and module loads for pretrain tasks

CUDA_VERSION_MAJOR=12
CUDA_VERSION_MINOR=8
CUDA_VERSION_PATCH=1

CUDA_VERSION=${CUDA_VERSION_MAJOR}.${CUDA_VERSION_MINOR}
CUDA_VERSION_SHORT=${CUDA_VERSION_MAJOR}${CUDA_VERSION_MINOR}
CUDNN_VERSION=9.5
CUDNN_VERSION_WITH_PATCH=9.5.1
HPCX_VERSION=2.20
NCCL_VERSION=2.25
NCCL_VERSION_WITH_PATCH=2.25.1-1

source /etc/profile.d/modules.sh
module load cuda/${CUDA_VERSION}/${CUDA_VERSION}.${CUDA_VERSION_PATCH}
module load cudnn/${CUDNN_VERSION}/${CUDNN_VERSION_WITH_PATCH}
module load hpcx/${HPCX_VERSION}
module load nccl/${NCCL_VERSION}/${NCCL_VERSION_WITH_PATCH}

export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH
